import eslint from '@eslint/js';
import stylistic from '@stylistic/eslint-plugin';
import globals from 'globals';
import importPlugin from 'eslint-plugin-import';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import unicorn from 'eslint-plugin-unicorn';
import tseslint from 'typescript-eslint';

import createNamingConventions from './eslint/naming-convention.js';
import noFilterMapCast from './eslint/no-filter-map-cast.js';
import noPromiseAllSettled from './eslint/no-promise-all-settled.js';

const off = 'off';
const error = 'error';
// Warnings are errors during build mode
const warn = process.env.NODE_ENV === 'production' ? error : 'warn';
const defaultNamingConventions = createNamingConventions(false);

export default [
  {
    ignores: [
      '**/*.js',
      '**/*.mjs',
      '**/*.cjs',
      '**/*.d.ts',
      '**/dist/**',
      '**/node_modules/**',
      '**/coverage/**',
    ],
  },
  eslint.configs.recommended,
  react.configs.flat.all,
  react.configs.flat['jsx-runtime'],
  ...tseslint.configs.recommended,
  importPlugin.flatConfigs.errors,
  importPlugin.flatConfigs.warnings,
  {
    settings: {
      react: {
        version: '18.3',
      },
      'import/parsers': {
        '@typescript-eslint/parser': ['.ts', '.tsx'],
      },
      'import/ignore': ['node_modules'],
    },
    linterOptions: {
      reportUnusedDisableDirectives: off,
    },
    languageOptions: {
      globals: globals.browser,
      parserOptions: {
        ecmaVersion: 'latest',
        ecmaFeatures: {
          jsx: true,
        },
      },
    },
  },
  {
    files: ['backend/**/*.ts'],
    languageOptions: { globals: globals.node },
  },
  {
    files: ['**/*.ts', '**/*.tsx'],
    plugins: {
      'react-hooks': reactHooks,
      '@stylistic': stylistic,
      unicorn,
      crystal: {
        rules: {
          'no-filter-map-cast': noFilterMapCast,
          'no-promise-all-settled': noPromiseAllSettled,
        },
      },
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      'crystal/no-filter-map-cast': error,
      'crystal/no-promise-all-settled': error,
      '@stylistic/arrow-spacing': warn,
      '@stylistic/block-spacing': warn,
      '@stylistic/brace-style': warn,
      '@stylistic/indent': [warn, 2, { SwitchCase: 1 }],
      '@stylistic/comma-dangle': [
        warn,
        {
          arrays: 'always-multiline',
          imports: 'always-multiline',
          objects: 'always-multiline',
          functions: 'always-multiline',
        },
      ],
      '@stylistic/comma-spacing': error,
      '@stylistic/comma-style': error,
      '@stylistic/dot-location': [error, 'property'],
      '@stylistic/function-call-spacing': error,
      '@stylistic/function-paren-newline': [error, 'multiline-arguments'],
      '@stylistic/jsx-quotes': warn,
      '@stylistic/keyword-spacing': warn,
      '@stylistic/no-extra-semi': error,
      '@stylistic/no-mixed-operators': warn,
      '@stylistic/no-multi-spaces': error,
      '@stylistic/no-tabs': error,
      '@stylistic/no-whitespace-before-property': error,
      '@stylistic/object-curly-spacing': [error, 'always'],
      '@stylistic/operator-linebreak': [error, 'before', { overrides: { '=': 'after' } }],
      '@stylistic/padded-blocks': [warn, 'never'],
      '@stylistic/quote-props': [warn, 'as-needed'],
      '@stylistic/quotes': [warn, 'single', { avoidEscape: true }],
      '@stylistic/rest-spread-spacing': error,
      '@stylistic/semi': [warn, 'always'],
      '@stylistic/semi-spacing': error,
      '@stylistic/semi-style': error,
      '@stylistic/space-before-blocks': error,
      '@stylistic/space-before-function-paren': off,
      '@stylistic/space-infix-ops': error,
      '@stylistic/space-unary-ops': error,
      '@stylistic/spaced-comment': warn,
      '@stylistic/switch-colon-spacing': error,
      '@stylistic/template-curly-spacing': error,
      '@stylistic/template-tag-spacing': error,
      '@stylistic/yield-star-spacing': error,
      '@typescript-eslint/array-type': [error, { default: 'array', readonly: 'generic' }],
      '@typescript-eslint/ban-types': off,
      '@typescript-eslint/camelcase': off,
      '@typescript-eslint/explicit-function-return-type': off,
      '@typescript-eslint/explicit-member-accessibility': [
        error,
        { accessibility: 'explicit', overrides: { constructors: 'no-public' } },
      ],
      '@typescript-eslint/explicit-module-boundary-types': off,
      '@typescript-eslint/member-ordering': warn,
      '@typescript-eslint/naming-convention': [error, ...defaultNamingConventions],
      '@typescript-eslint/no-array-constructor': error,
      '@typescript-eslint/no-empty-function': off,
      '@typescript-eslint/no-empty-interface': [error, { allowSingleExtends: true }],
      '@typescript-eslint/no-empty-object-type': off,
      '@typescript-eslint/no-explicit-any': off,
      '@typescript-eslint/no-extra-non-null-assertion': error,
      '@typescript-eslint/no-extraneous-class': error,
      '@typescript-eslint/no-floating-promises': off,
      '@typescript-eslint/no-invalid-void-type': off,
      '@typescript-eslint/no-misused-promises': off,
      '@typescript-eslint/no-namespace': [error, { allowDeclarations: true }],
      '@typescript-eslint/no-non-null-asserted-optional-chain': error,
      '@typescript-eslint/no-non-null-assertion': off,
      '@typescript-eslint/no-require-imports': off,
      '@typescript-eslint/no-throw-literal': off,
      '@typescript-eslint/no-unsafe-assignment': off,
      '@typescript-eslint/no-unsafe-call': off,
      '@typescript-eslint/no-unused-expressions': error,
      '@typescript-eslint/no-unsafe-function-type': off,
      '@typescript-eslint/no-unsafe-return': off,
      '@typescript-eslint/no-unsafe-member-access': off,
      '@typescript-eslint/no-unused-vars': off,
      '@typescript-eslint/no-use-before-define': [error, { functions: false, classes: false }],
      '@typescript-eslint/no-var-requires': error,
      '@typescript-eslint/parameter-properties': off,
      '@typescript-eslint/prefer-as-const': error,
      '@typescript-eslint/prefer-function-type': error,
      '@typescript-eslint/prefer-for-of': off,
      '@typescript-eslint/prefer-namespace-keyword': error,
      '@typescript-eslint/prefer-optional-chain': off,
      '@typescript-eslint/promise-function-async': off,
      '@typescript-eslint/restrict-plus-operands': off,
      '@typescript-eslint/return-await': off,
      'arrow-body-style': off,
      'array-bracket-spacing': [error, 'never'],
      'arrow-spacing': error,
      'block-scoped-var': error,
      'block-spacing': error,
      'capitalized-comments': [warn, 'always', { ignoreConsecutiveComments: true, ignoreInlineComments: true }],
      'computed-property-spacing': error,
      curly: error,
      'dot-notation': error,
      eqeqeq: [error, 'smart'],
      'import/default': off,
      'import/export': off,
      'import/named': off,
      'import/namespace': off,
      'import/newline-after-import': warn,
      'import/no-named-as-default': off,
      'import/no-named-as-default-member': off,
      'import/no-unresolved': off,
      'import/order': [
        warn,
        {
          pathGroups: [
            { pattern: 'react', group: 'external', position: 'before' },
            { pattern: 'react-router-dom', group: 'external' },
            {
              pattern: '*.styles',
              patternOptions: { matchBase: true },
              group: 'sibling',
              position: 'after',
            },
          ],
          pathGroupsExcludedImportTypes: ['builtin', 'react'],
          groups: ['builtin', 'external', 'unknown', 'internal', 'parent', 'index', 'object', 'sibling'],
        },
      ],
      'no-array-constructor': off,
      'no-caller': error,
      'no-console': warn,
      'no-control-regex': off,
      'no-constant-condition': [warn, { checkLoops: false }],
      'no-constructor-return': error,
      'no-else-return': error,
      'no-labels': error,
      'no-lonely-if': error,
      'no-multiple-empty-lines': [warn, { max: 1, maxEOF: 0, maxBOF: 0 }],
      'no-new-object': error,
      'no-new-wrappers': error,
      'no-return-await': off,
      'no-template-curly-in-string': error,
      'no-undef-init': error,
      'no-unneeded-ternary': error,
      'no-unused-expressions': off,
      'no-unused-vars': off,
      'no-useless-concat': error,
      'object-property-newline': [error, { allowAllPropertiesOnSameLine: true }],
      'object-shorthand': error,
      'prefer-const': [error, { destructuring: 'all' }],
      'prefer-numeric-literals': error,
      'prefer-rest-params': error,
      'prefer-template': off,
      'react/default-props-match-prop-types': off,
      'react/destructuring-assignment': off,
      'react/display-name': off,
      'react/iframe-missing-sandbox': off,
      'react/forbid-component-props': off,
      'react/forbid-prop-types': off,
      'react/function-component-definition': off,
      'react/jsx-closing-bracket-location': warn,
      'react/jsx-curly-brace-presence': error,
      'react/jsx-filename-extension': [error, { extensions: ['.tsx', '.jsx'] }],
      'react/jsx-indent': [warn, 2, { checkAttributes: true, indentLogicalExpressions: true }],
      'react/jsx-indent-props': [warn, 2],
      'react/jsx-max-depth': off,
      'react/jsx-max-props-per-line': [warn, { when: 'multiline' }],
      'react/jsx-newline': off,
      'react/jsx-no-bind': off,
      'react/jsx-no-constructed-context-values': off,
      'react/jsx-no-leaked-render': off,
      'react/jsx-no-literals': off,
      'react/jsx-no-useless-fragment': off,
      'react/jsx-one-expression-per-line': off,
      'react/jsx-props-no-spreading': off,
      'react/jsx-sort-props': [warn, { callbacksLast: true, reservedFirst: true, shorthandFirst: true }],
      'react/jsx-tag-spacing': [
        warn,
        { closingSlash: 'never', beforeSelfClosing: 'always', afterOpening: 'never', beforeClosing: 'never' },
      ],
      'react/jsx-wrap-multilines': [
        error,
        {
          declaration: 'parens-new-line',
          assignment: 'parens-new-line',
          return: 'parens-new-line',
          arrow: 'parens-new-line',
          condition: 'parens-new-line',
          logical: 'parens-new-line',
          prop: 'parens-new-line',
        },
      ],
      'react/no-multi-comp': off,
      'react/no-array-index-key': off,
      'react/no-danger': off,
      'react/no-did-mount-set-state': off,
      'react/no-did-update-set-state': off,
      'react/no-find-dom-node': off,
      'react/no-set-state': off,
      'react/no-unstable-nested-components': [error, { allowAsProps: true }],
      'react/no-unused-class-component-methods': off,
      'react/no-unused-prop-types': off,
      'react/prefer-read-only-props': off,
      'react/prefer-stateless-function': off,
      'react/prop-types': off,
      'react/react-in-jsx-scope': off,
      'react/require-default-props': off,
      'react/require-optimization': off,
      'react/sort-comp': off,
      'react/static-property-placement': off,
      'react-hooks/exhaustive-deps': off,
      'require-await': off,
      'sort-imports': [warn, { ignoreDeclarationSort: true, memberSyntaxSortOrder: ['all', 'single', 'multiple', 'none'] }],
      'unicorn/better-regex': error,
      'unicorn/catch-error-name': error,
      'unicorn/filename-case': [warn, { cases: { camelCase: true, pascalCase: true } }],
      'unicorn/prefer-add-event-listener': error,
      'unicorn/prefer-array-find': error,
      'unicorn/prefer-array-flat': error,
      'unicorn/prefer-array-flat-map': error,
      'unicorn/prefer-array-index-of': error,
      'unicorn/prefer-array-some': error,
      'unicorn/prefer-date-now': error,
      'unicorn/prefer-default-parameters': error,
      'unicorn/prefer-dom-node-append': error,
      'unicorn/prefer-dom-node-remove': error,
      'unicorn/prefer-dom-node-text-content': error,
      'unicorn/prefer-includes': error,
      'unicorn/prefer-negative-index': error,
      'unicorn/prefer-number-properties': error,
      'unicorn/prefer-set-has': error,
      'unicorn/prefer-string-slice': error,
      'unicorn/prefer-string-starts-ends-with': error,
      'unicorn/prefer-string-trim-start-end': error,
    },
  },
];
