-- PostgreSQL schema. CREATE statements are idempotent so an empty database
-- can be initialized repeatedly before the idempotent demo seed is applied.

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role TEXT NOT NULL CHECK (role IN ('teacher', 'parent', 'admin')),
  name TEXT NOT NULL,
  email TEXT UNIQUE,
  password_hash TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS classes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  teacher_id INTEGER NOT NULL REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS students (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  display_name TEXT NOT NULL,
  avatar_key TEXT NOT NULL,
  class_id INTEGER NOT NULL REFERENCES classes(id),
  parent_id INTEGER REFERENCES users(id),
  parent_quick_code TEXT UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS plants (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  qr_code TEXT NOT NULL UNIQUE,
  image_path TEXT,
  benefit_text TEXT,
  is_published BOOLEAN NOT NULL DEFAULT FALSE,
  created_by INTEGER REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS recipes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  image_path TEXT,
  is_published BOOLEAN NOT NULL DEFAULT FALSE,
  created_by INTEGER REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS recipe_steps (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipe_id INTEGER NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
  step_order INTEGER NOT NULL,
  image_path TEXT,
  step_text TEXT,
  UNIQUE (recipe_id, step_order)
);

CREATE TABLE IF NOT EXISTS recipe_plants (
  recipe_id INTEGER NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
  plant_id INTEGER NOT NULL REFERENCES plants(id) ON DELETE CASCADE,
  PRIMARY KEY (recipe_id, plant_id)
);

CREATE TABLE IF NOT EXISTS cookbook_entries (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id INTEGER NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  recipe_id INTEGER NOT NULL REFERENCES recipes(id),
  added_by TEXT NOT NULL CHECK (added_by IN ('student', 'teacher', 'parent')),
  is_made BOOLEAN NOT NULL DEFAULT FALSE,
  made_at TIMESTAMPTZ,
  rating INTEGER CHECK (rating IS NULL OR rating BETWEEN 1 AND 3),
  rated_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (student_id, recipe_id)
);

CREATE TABLE IF NOT EXISTS plant_discoveries (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id INTEGER NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  plant_id INTEGER NOT NULL REFERENCES plants(id),
  first_scanned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_scanned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (student_id, plant_id)
);

CREATE TABLE IF NOT EXISTS garden_selections (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id INTEGER NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
  plant_id INTEGER NOT NULL REFERENCES plants(id),
  selected_by INTEGER REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (class_id, plant_id)
);

CREATE TABLE IF NOT EXISTS activity_log (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_type TEXT NOT NULL CHECK (actor_type IN ('student', 'teacher', 'parent', 'admin')),
  actor_id INTEGER NOT NULL,
  action TEXT NOT NULL,
  content_type TEXT,
  content_id INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS session (
  sid VARCHAR PRIMARY KEY,
  sess JSON NOT NULL,
  expire TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_activity_log_created_at ON activity_log(created_at);
CREATE INDEX IF NOT EXISTS idx_students_class_id ON students(class_id);
CREATE INDEX IF NOT EXISTS idx_students_parent_id ON students(parent_id);
CREATE INDEX IF NOT EXISTS idx_cookbook_entries_student_id ON cookbook_entries(student_id);
CREATE INDEX IF NOT EXISTS idx_plant_discoveries_student_id ON plant_discoveries(student_id);
CREATE INDEX IF NOT EXISTS idx_session_expire ON session(expire);
